### ISSUE TITLE
function signature bug with star_arg

### ISSUE THREAD

**Issue by rocky** [rocky/python-decompile3#10]
```
def test9(x=55, *varargs: int, y=5, **kwargs):
    pass 
```
deparses as:

```
def test9(x=55, *y: int, y=5, **kwargs):
    pass 
```

The bug is somewhere in [make_function.py](https://github.com/rocky/python-decompile3/blob/master/decompyle3/semantics/make_function.py#L659-L666)

We most likely have the same bug in uncompyle6.

**Comment by x0ret** [comment]
I will port [uncompyle6 #259 PR](https://github.com/rocky/python-uncompyle6/pull/259) here and i think this issue will be fixed.
