### ISSUE TITLE
Wrong decompilation with dictionary comprehension

### ISSUE THREAD

**Issue by mfkasim1** [rocky/python-decompile3#104]
## Description

The following code, when compiled and decompiled using decompyle3, returns the wrong results.
```python
def getargs(args):
    for i in range(10):
        _ = {key: val[i] for (key, val) in args.items()}
```

The decompiled code (after compilation with `py_compile`) looks like below (I removed the header for clarity, but I will mention my specs later): 
```python
def getargs(args):
    for i in range(10):
        _ = {val[i]: key for key, val in }
```

## How to Reproduce

* Save the original code in some file, say `test.py`
* `$ decompyle3 test.py` and you will see the results above

## Output Given

Here's the decompiled code (just like above):
```python
def getargs(args):
    for i in range(10):
        _ = {val[i]: key for key, val in }
```
It produces a syntatically wrong code (by missing `args.items()`) and semantically wrong (by swapping key and value).

## Expected behavior

The decompiled code should produce syntactically and semantically right code.

## Environment

- Decompyle3 version: 3.9.0
- Python version for the version of Python the byte-compiled the file: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:53:36) [GCC 9.4.0]
- OS and Version: Ubuntu 18.04.5 LTS (bionic)

-->

## Workarounds

The results can be corrected by using `dict` instead of just the bracket `{`, e.g.
```python
def getargs(args):
    for i in range(10):
        _ = dict((key, val[i]) for (key, val) in args.items())
```

## Priority

Not a high priority for me because there is a workaround. However, with the swapping of key and value, is there a way to check if the decompiled code produces the same semantic as the original one?

## Additional Context

After playing around with the codes, I realized there are 2 different problems. First is like above, with dictionary comprehension and for loop, the key-value positions are swapped (key becomes value and value becomes key) and `args.items()` is missing. The second case is if there is no loop, the key-value positions are still swapped, but `args.items()` is there.

To put it in an example, the decompylation of this code:
```python
def getargs(args):
    _ = {key: val for (key, val) in args.items()}
```
Becomes this one:
```python
def getargs(args):
    _ = {val: key for key, val in args.items()}
```

**Comment by rocky** [comment]
Thanks for the detailed and clear bug report. I think this has been fixed now. If not reopen the issue.

The same thing needs to be done in uncompyle6 if you are up for making that PR. (And it might be instructive to do to get a sense of how the code works.)

> is there a way to check if the decompiled code produces the same semantic as the original one?

In the general and theoretical situation, this undecidable, googling turns up https://www.cs.rochester.edu/u/nelson/courses/csc_173/computability/undecidable.html for example. 

The extent to which those results hold here in this particular situation is unknown. There was a time back around Python 1.5-2.2 bytecode compilation was so simplistic an ancestor version of this code thought that it _could_ detect equivalence.  Those days are long gone though. 

From a practical matter, what you should do is write (or find) a test for the module you have decompiled and verify (but not prove things that way).  

And you will see a _lot_ of test cases in this repository. Hey, I just added one for this bug.
