### ISSUE TITLE
Typo in latest pip version (3.9.0)

### ISSUE THREAD

**Issue by Svenskithesource** [rocky/python-decompile3#113]
## Description

There's a typo in the help command in the latest pip version (3.9.0). It says "byecode" instead of "bytecode".
## How to Reproduce
Install decompyle3 from pip and run `decompyle3 --help`

## Output Given
```console
$ decompyle3 --help
Usage: decompyle3 [OPTIONS] FILES...

  Python byecode decompiler for 3.10 bytecode

Options:
  -a, --asm / --no-asm
  -g, --grammar / --no-grammar
  -t, --tree / --no-tree
  -T, --tree++ / --no-tree++
  --verify [run|syntax]
  -r, --recurse / --no-recurse
  -o, --output PATH
  --version                     Show the version and exit.
  --help                        Show this message and exit.
```

## Expected behavior
```console
$ decompyle3 --help
Usage: decompyle3 [OPTIONS] FILES...

  Python bytecode decompiler for 3.10 bytecode

Options:
  -a, --asm / --no-asm
  -g, --grammar / --no-grammar
  -t, --tree / --no-tree
  -T, --tree++ / --no-tree++
  --verify [run|syntax]
  -r, --recurse / --no-recurse
  -o, --output PATH
  --version                     Show the version and exit.
  --help                        Show this message and exit.
```

**Comment by Svenskithesource** [comment]
Also while filing this bug I noticed there are multiple typos in your bug form template. I'd recommend you to run it through Word or Grammarly to fix all vocabulary and grammar issues 👍

**Comment by rocky** [comment]
The typo you mention is not in the current master, but we don't decompile 3.10, just 3.7-3.8 so that's been adjusted. 

As for typos in the template, thanks for letting me know.  At some point I'll get around to it. 

If you want to make a PR for the corrections the file is https://github.com/rocky/python-decompile3/tree/master/.github/ISSUE_TEMPLATE
