### ISSUE TITLE
python-decompile3-master

### ISSUE THREAD

**Issue by maxgregier** [rocky/python-decompile3#139]
## Error invalid value
When I run "python-decompile3-master" it's end always with the following error (attached is a print screen of the error):
Error: Invalid value for '--output' / '-o': Path 'result/source_code.py' does not exist.
How can this error be resolved?
Thank you in advance for your help.

## Background

![Python decompile3 master-Error](https://github.com/rocky/python-decompile3/assets/136501353/0c4973d2-e9bb-4544-882e-a162063fa123)

## Priority

 High priority

**Comment by rocky** [comment]
This looks like a problem in some pipeline or wrapping code than it is about running decompyle3. The error message seems to indicate that the program was called incorrectly from the pipeline. 

One other thing for the future.  For  the priority to be anything other than the lowest priority, you must justify _why_ this is something other than that. Priority is not about important _you_ feel about the problem, but rather a justification as to why I and others should be interested in this.

**Comment by rocky** [comment]
Read the third paragraph of https://github.com/rocky/python-decompile3/issues/new?assignees=&labels=&projects=&template=bug-report.md
