### ISSUE TITLE
Got error "Deparsing stopped due to parse error"

### ISSUE THREAD

**Issue by JennrCheng** [rocky/python-decompile3#142]
Hi Sir,
When I decompile a file which compiled with python 3.7.4 , I got this error
`# file colle.pyc
# Deparsing stopped due to parse error
colle.pyc --
# decompile failed`

The files link is below:
[http://pan.wucuoym.com/pyc.zip](url)

May you help me check it ,Thank you.

**Comment by rocky** [comment]
Please don't us links to sites. Attach the zip file here. Also fill out The sections in https://github.com/rocky/python-decompile3/blob/master/.github/ISSUE_TEMPLATE/bug-report.md
