### ISSUE TITLE
Unsupported Python version, 3.11, for decompilation

### ISSUE THREAD

**Issue by vkchahar** [rocky/python-decompile3#169]
uncompyle6 version 3.9.1
Python bytecode version base 3.11 (3495)
 Decompiled from: Python 3.11.0 (main, Mar 23 2024, 20:50:59) [GCC 9.4.0]
 Embedded file name: DataChain_V2.py
 Compiled at: 2023-11-09 15:49:25
 Size of source mod 2**32: 17856 bytes

Unsupported Python version, 3.11, for decompilation

 Unsupported bytecode in file DataChain_V2.pyc
 Unsupported Python version, 3.11, for decompilation

**Comment by Selveshwaran** [comment]
I too have the same issue

**Comment by rocky** [comment]
> I too have the same issue

You too don't bother to read before you post.
