### ISSUE TITLE
Tree transformation phase is not adding semantic function customization rules.

### ISSUE THREAD

**Issue by rocky** [rocky/python-decompile3#22]
Consider this program taken for `01_fstring.py`:

```python
def _repr_fn(fields):
    return testit('__repr__',
                  ('self',),
                  ['return xx + f"(' +
                   ', '.join([f"{f}={{self.{f}!r}}"
                              for f in fields]) +
                   ')"'])
```

Pre commmit 1aa6f00 this was not decompiing properly because there was no semantic rule for `CALL_METHOD_1`  so the `testit` call `(`, ')`  and `,` disappear. 

If you uncomment out https://github.com/rocky/python-decompile3/commit/1aa6f008c40f98edd64a0e42c74ae9f549eca98a#diff-1d363324084c476e417a8c8da17df69cR410 you will see `CALL_METHOD_1` appearing in `customize` the set of semantic action rules that need to be customized. 

However if you now uncomment the code that starts at https://github.com/rocky/python-decompile3/commit/1aa6f008c40f98edd64a0e42c74ae9f549eca98a#diff-02b4d783e57c0af1f6663933c6f45599R2321 you will see that all of this disappears. 

So something in doing the tree transformation is not adding the customization and/or prevents the non transform pass from adding it. 

Conceptually, I understand why this might be: the first filter pass might not fully traverse the ast tree and follow all code that gets generated. However it might also a problem of removing as well as not adding. There are places like https://github.com/rocky/python-decompile3/commit/1aa6f008c40f98edd64a0e42c74ae9f549eca98a#diff-1d363324084c476e417a8c8da17df69cR413 which do remove customization items. 

@x0ret  Would you look at this? If you don't have time or don't want to let me know and I will fix when I get a chance. Thanks!

**Comment by rocky** [comment]
@x0ret  Thought and looked again a little bit more. I think the fix might be to do call transform from [gen_source around here](https://github.com/rocky/python-decompile3/blob/tree-transform/decompyle3/semantics/pysource.py#L2175)

**Comment by x0ret** [comment]
@rocky thanks for looking into this. Unfortunately i'm currently in middle of something heavy :( . I'm going to handle this tomorrow. Thanks again.

**Comment by rocky** [comment]
Handled now in merge of 7b0c7d5c
