### ISSUE TITLE
ImportError: Ill-formed bytecode file

### ISSUE THREAD

**Issue by DjarDjar** [rocky/python-decompile3#26]
I have problem with decompiling an exe. I kinda deleted the wrong folder and now Im left with the exe, made by pyinstaller and nothing else. So basically I googled how to decompile pyinstaller exes and I found that first I use this: https://github.com/countercept/python-exe-unpacker/blob/master/pyinstxtractor.py to convert to .pyc files and then:

`uncompyle6: (It turns out that this one isn't supported, so then I found decompyle3, though a stackoverflow question.)`
to get the source. The problem is that pyinstxtractor doesn't return the source code in .pyc format so I basically had to convert it myself and then add the "magic numbers" to it so that decompyle3 sees it as .pyc. So then I write

`decompyle3 name_of_pyc.pyc`
and i get this error: https://prnt.sc/q4r0my. I know that has something to do with the python version but please help, I don't wanna lose my work lmao.

**Comment by rocky** [comment]
What Python version was the program written in?

**Comment by DjarDjar** [comment]
> What Python version was the program written in?

Python 3.7

**Comment by rocky** [comment]
Ok. Then this is the right repository to use _when you have valid bytecode._  

I'm sorry you lost your source code. Elsewhere I have where you might be able to pay someone to try to reconstruct your bytecode and source code. 

Here's a pro-tip for opening bugs both here and in other projects I run: when asking for help, it's probably a good idea to read the instructions and follow as them as best as possible. 

For example, when you opened this issue there was a template given to follow, which included things like indicating what version you are using. 

I'm sorry I don't have time for an interactive dialog to get information that is supposed to be given up front; I need to spend my time elsewhere.

**Comment by DjarDjar** [comment]
> Ok. Then this is the right repository to use _when you have valid bytecode._
> 
> I'm sorry you lost your source code. Elsewhere I have where you might be able to pay someone to try to reconstruct your bytecode and source code.
> 
> Here's a pro-tip for opening bugs both here and in other projects I run: when asking for help, it's probably a good idea to read the instructions and follow as them as best as possible.
> 
> For example, when you opened this issue there was a template given to follow, which included things like indicating what version you are using.
> 
> I'm sorry I don't have time for an interactive dialog to get information that is supposed to be given up front; I need to spend my time elsewhere.

Right, sorry for not specifying the python version in the description, I was just too frustrated to read the whole thing, but thanks for the pro tip. So about what you're saying, what tool would you recommend to get the valid bytecode.

**Comment by rocky** [comment]
http://www.crazy-compilers.com/decompyle/
