### ISSUE TITLE
This package is not supported for Python version

### ISSUE THREAD

**Issue by dima-online** [rocky/python-decompile3#39]
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
Python 3.6.9

root@ubuntu:/opt/python-decompile3# pip install -e .
Obtaining file:///opt/python-decompile3
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/python-decompile3/setup.py", line 8
        mess = f"\nThis package is not supported for Python version {sys.version[0:3]}."
                                                                                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /opt/python-decompile3/

**Comment by rocky** [comment]
Yes python-decompile3 is not supported on 3.6 and it says so in https://github.com/rocky/python-decompile3#requirements
