### ISSUE TITLE
Parse error at or near `POP_TOP' instruction (Python 3.8)

### ISSUE THREAD

**Issue by yuan824** [rocky/python-decompile3#43]
When I decompiled the pyc, got the following error messages. I had the source code & the script was quite short.
Could you please help to check the issue.
Thanks.

**Environment:**
Win10 with Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)] on win32

**Reproduce the error:**
D:\__pycache__>c:Scripts\decompyle3.exe t38.cpython-38.pyc
\# decompyle3 version 3.3.2
\# Python bytecode 3.8 (3413)
\# Decompiled from: Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
\# Embedded file name: d:/t38.py
\# Compiled at: 2020-08-14 14:49:04
\
[t38.py.txt](https://github.com/rocky/python-decompile3/files/5073103/t38.py.txt)
[t38.zip](https://github.com/rocky/python-decompile3/files/5073109/t38.zip)
[t38.zip](https://github.com/rocky/python-decompile3/files/5073116/t38.zip)

# Size of source mod 2**32: 197 bytes
Instruction context:

 L.  12        36  POP_TOP
->                38  POP_TOP
                  40  LOAD_CONST               0
                  42  RETURN_VALUE
                  44  JUMP_BACK            24  'to 24'
                46_0  COME_FROM            24  '24'
                  46  JUMP_BACK            16  'to 16'
                48_0  COME_FROM            16  '16'
gnb = False
li = [1, 2, 4]

def aa--- This code section failed: ---

 L.   5         0  LOAD_GLOBAL              gnb
                2  POP_JUMP_IF_FALSE     8  'to 8'

 L.   6         4  LOAD_CONST               0
                6  RETURN_VALUE
              8_0  COME_FROM             2  '2'

 L.   8         8  LOAD_STR                 'abc'
               10  STORE_FAST               'str'

 L.   9        12  LOAD_FAST                'str'
               14  GET_ITER
             16_0  COME_FROM            46  '46'
               16  FOR_ITER             48  'to 48'
               18  STORE_FAST               'c'

 L.  10        20  LOAD_GLOBAL              li
               22  GET_ITER
             24_0  COME_FROM            44  '44'
             24_1  COME_FROM            34  '34'
               24  FOR_ITER             46  'to 46'
               26  STORE_FAST               'n'

 L.  11        28  LOAD_FAST                'n'
               30  LOAD_CONST               1
               32  COMPARE_OP               ==
               34  POP_JUMP_IF_FALSE_BACK    24  'to 24'

 L.  12        36  POP_TOP
               38  POP_TOP
               40  LOAD_CONST               0
               42  RETURN_VALUE
               44  JUMP_BACK            24  'to 24'
             46_0  COME_FROM            24  '24'
               46  JUMP_BACK            16  'to 16'
             48_0  COME_FROM            16  '16'

 L.  13        48  LOAD_CONST               1
               50  RETURN_VALUE
               -1  RETURN_LAST

Parse error at or near `POP_TOP' instruction at offset 38

aa()

\# file t38.cpython-38.pyc
\# Deparsing stopped due to parse error

**Comment by nedogimov** [comment]
Not fix.
