### ISSUE TITLE
Push on pypi?

### ISSUE THREAD

**Issue by JulienPalard** [rocky/python-decompile3#48]
## Description

Just an interrogation, why https://pypi.python.org/pypi/uncompyle6 but no https://pypi.python.org/pypi/uncompyle3?

**Comment by rocky** [comment]
Right now, I don't have a need for a PyPI package, and releases are an effort, and this project is "funded" by my own volunteer free time which is vanishing (or rather has vanished). 

As some point in the back of my mind was to completely do another major overhaul for 3.9 with reverse dominitors to assist in control flow for. 

Were that to succeed it would subsume this. However in reality this will have to hang out for a while.



Things of course can change.

**Comment by JulienPalard** [comment]
Hi!

Thanks for the answer!

While I'm here, thanks for all the work on python-decompile!

Bests.
