### ISSUE TITLE
I get an the end a error code named Parse error at or near END_FINALLY instruction at offset 3124

### ISSUE THREAD

**Issue by mrgrupprr** [rocky/python-decompile3#54]
my python version is 3.8 and I got the pyc decompiled from a exe with python-to-exe than I added the magic number.

here is another info may be needed:

OS : win 10
Python 3.8.5
deompile3: newest version right now
Python bytecode 3.8 (3413)
Source code size mod 2**32

issue : I get an the end a error code named Parse error at or near END_FINALLY instruction at offset 3124.

The first picture is when it starts
the second is the error
the 3 thing is the File I try to get the source of
![vmware_YEhLGsUoDQ](https://user-images.githubusercontent.com/70100389/110478917-20239100-80e5-11eb-936e-e1b26b74ac2c.png)
![vmware_MQKIx8uY21](https://user-images.githubusercontent.com/70100389/110478930-231e8180-80e5-11eb-908a-6199a88bd845.png)

This is the the thing I tired to get the source of: https://anonfiles.com/fd33Dcy6r6/Nighty_pyc

**Comment by eyal9** [comment]
I got the same error...

**Comment by eyal9** [comment]
Actually, mine's a little different:  `AttributeError: module 'xdis.opcodes.opcode_39' has no attribute 'END_FINALLY'`

**Comment by BentoNight** [comment]
Same problem

**Comment by dabucz** [comment]
BTW Nighty have Pyarmor so you cant decompyle it

**Comment by jpgami21** [comment]
Its a old version that can be decompilied.

**Comment by rocky** [comment]
This pyc file can't be retrieved any longer. So if this is still of interest, attach it.
