### ISSUE TITLE
python 3.8 erro

### ISSUE THREAD

**Issue by levanhau03** [rocky/python-decompile3#56]
`Instruction context:
   
 L. 339       156  POP_BLOCK        
                 158  JUMP_BACK            40  'to 40'
->             160_0  COME_FROM           154  '154'
               160_1  COME_FROM           134  '134'
               160_2  COME_FROM           122  '122'
                 160  POP_BLOCK        
                 162  JUMP_BACK            40  'to 40'
               164_0  COME_FROM_FINALLY    62  '62'
Instruction context:
-> 
 L. 725       206  LOAD_GLOBAL              cytus_img
                 208  LOAD_FAST                'able_file'
                 210  CALL_FUNCTION_1       1  ''
                 212  POP_TOP          
               214_0  COME_FROM           194  '194'
                 214  JUMP_BACK           118  'to 118'
               216_0  COME_FROM           118  '118'
Instruction context:
-> 
 L. 903       250  LOAD_FAST                'able'
                 252  LOAD_CONST               2
                 254  COMPARE_OP               ==
             256_258  POP_JUMP_IF_FALSE   360  'to 360'
Instruction context:
-> 
 L.1214       380  LOAD_GLOBAL              ErrorsFunction
                 382  CALL_FUNCTION_0       0  ''
                 384  POP_TOP          
               386_0  COME_FROM           248  '248'`
[rna.zip](https://github.com/rocky/python-decompile3/files/6326768/rna.zip)

**Comment by rocky** [comment]
> I'm willing to donate if the author helps me decompile this file, I really need them how can i contact?

Private consulting available via https://calendly.com/rb3216 rates: $150/30 minutes; $250/60 minutes
