### ISSUE TITLE
AttributeError: module 'xdis.opcodes.opcode_39' has no attribute 'END_FINALLY'

### ISSUE THREAD

**Issue by Gowixx** [rocky/python-decompile3#65]
AttributeError: module 'xdis.opcodes.opcode_39' has no attribute 'END_FINALLY'

**Comment by rocky** [comment]
Read https://github.com/rocky/python-decompile3/issues/new?assignees=&labels=&template=bug-report.md
and https://docs.python.org/3/library/dis.html?highlight=opcode#python-bytecode-instructions
