### ISSUE TITLE
PYPI Page Links to Incorrect Github URL

### ISSUE THREAD

**Issue by atmaranto** [rocky/python-decompile3#74]
The Homepage link at https://pypi.org/project/decompyle3/ seems to be invalid. It links to https://github.com/rocky/python-decompyle3/ (which does not exist) rather than this repo. I assume this was because decompile is spelled here with an "i" and there with a "y"; from what I can tell, there is no PYPI repo for "decompile3".

Sorry if this isn't the proper place to report this; I assume this is relevant to the project, even if it isn't relevant to the project's code.

**Comment by rocky** [comment]
This is the correct place for this. Thanks for reporting and your attention to detail.

However the change will be visible in PyPI will only be visible after the next release.
