### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Zinovich** [rocky/python-decompile3#79]
![image](https://user-images.githubusercontent.com/70067052/146356925-90c6f185-1b8f-403f-98b8-a65026fab89f.png)

**Comment by rocky** [comment]
You are running uncompyle6 and this is the decompyle3 issue tracker. Also, before opening a bug report read and follow the instructions that are given when you open a new bug report. A more detailed description is found in [HOW-TO-REPORT-A-BUG](https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md). See especially the section on "do you have valid bytecode".
