### ISSUE TITLE
So much for working with 3.8 and above..

### ISSUE THREAD

**Issue by moribundant** [rocky/python-decompile3#89]
bash-3.2$ decompyle3 -h
I don't know about Python version '3.9.10' yet.
Python versions 3.9 and greater are not supported.
I don't know about Python version '3.9.10' yet.
Python versions 3.9 and greater are not supported.
I don't know about Python version '3.9.10' yet.
Python versions 3.9 and greater are not supported.
I don't know about Python version '3.9.10' yet.
Python versions 3.9 and greater are not supported.
Error: decompyle3 can decompile only bytecode from Python 3.7 to 3.8.
	You have version: 3.9.10.

**Comment by rocky** [comment]
Thanks for your interest. It has been noted in https://github.com/rocky/python-decompile3/issues/45#issuecomment-1057297619
