### ISSUE TITLE
I get an the end a error code named"Parse error at or near `JUMP_LOOP' instruction at offset 200"

### ISSUE THREAD

**Issue by leejshades** [rocky/python-decompile3#91]
my python version is 3.8 and I got the pyc decompiled from a exe with python-to-exe than I added the magic number.

here is another info may be needed:

OS : win 10
Python 3.8.0
decompyle3, version 3.9.0a1
Python bytecode 3.8 (3413)
Source code size mod 2**32

issue : I get an the end a error code named"Parse error at or near `JUMP_LOOP' instruction at offset 200".

The first picture is when it starts
![image](https://user-images.githubusercontent.com/7189444/163514711-3e0b1756-83ee-4a50-ae20-60d263fc8874.png)

the second is the error
![image](https://user-images.githubusercontent.com/7189444/163514748-1e5a03b1-2d37-41f5-bd61-0aa8d0fe0f2b.png)

the 3 thing is the File I try to get the source of
https://github.com/leejshades/ActiveIQHealthManager/blob/master/PYZ-00.pyz_extracted/OntapHealthCheckTool.pyc

**Comment by rocky** [comment]
Unfortunately, this isn't enough information. For a bug report here we need to start out with _valid_ python, not something that using some process that might be turned into valid Python fix that and attach the bytecode here.

**Comment by leejshades** [comment]
here is pyc file.
https://github.com/leejshades/ActiveIQHealthManager/blob/master/PYZ-00.pyz_extracted/OntapHealthCheckTool.pyc

**Comment by rocky** [comment]
This is not valid python. Reread and follow the instructions in https://github.com/rocky/python-decompile3/issues/new?assignees=&labels=&template=bug-report.md more carefully.
