### ISSUE TITLE
`from a.b import c as d` decompiles wrongly

### ISSUE THREAD

**Issue by jnohlgard** [rocky/python-decompile3#92]
## Description

Import statements on the form `from a.b import c as d` become `import a.b as d` when decompiled. The disassembly contains all of the given package and module names, but the decompiler forgets to add module name from after the `import` in the original code.

Note that this problem only occurs when there is a dot in the package name. `from a import b as c` produces correct results.

## How to Reproduce

import-bug.py:

```python
from a.b import c as d
```

Running:

```console
$ decompyle3 ./import-bug.py
```

## Output Given

```python
# decompyle3 version 3.9.0a1
# Python bytecode version base 3.7.0 (3394)
# Decompiled from: Python 3.7.13 (default, Mar 18 2022, 11:41:25) 
# [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
# Embedded file name: ./import-bug.py
# Compiled at: 2022-04-20 16:08:48
# Size of source mod 2**32: 23 bytes
import a.b as d
# okay decompiling ./import-bug.py
```

## Expected behavior

Expected the decompiled result to be identical to the trivial input source.

## Environment

- Decompyle3 version: latest master, `decompyle3, version 3.9.0a1`
- Python version for the version of Python the byte-compiled the file: `3.7.13 (default, Mar 18 2022, 11:41:25) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]`
- OS and Version: Fedora 35

## Workarounds

Tedious and time-consuming manual checking of all import disassembly.

## Additional Context

The bug may be related to how `IMPORT_NAME_ATTR` is handled. The alternative `from a import c as d` uses `IMPORT_NAME`.

```
$ py3disassemble ./import-bug.py
# Python (3, 7, 0)
# Embedded file name: ./import-bug.py

 L.   1         0  LOAD_CONST               0
                2  LOAD_CONST               ('c',)
                4  IMPORT_NAME_ATTR         a.b
                6  IMPORT_FROM              c
                8  STORE_NAME               d
               10  POP_TOP          
               12  LOAD_CONST               None
               14  RETURN_VALUE     
```

```
$ py3disassemble ./import-nobug.py
# Python (3, 7, 0)
# Embedded file name: ./import-nobug.py

 L.   1         0  LOAD_CONST               0
                2  LOAD_CONST               ('c',)
                4  IMPORT_NAME              a
                6  IMPORT_FROM              c
                8  STORE_NAME               d
               10  POP_TOP          
               12  LOAD_CONST               None
               14  RETURN_VALUE
```

**Comment by rocky** [comment]
See if cb21cd52448cf241533785afacefea1b7dd55092 address this. If so, close the issue.

**Comment by jnohlgard** [comment]
That commit fixes the problem for the test in this thread as well as the file that I was working on originally when I stumbled upon the bug. Thank you for the swift fix :+1:
